### ISSUE TITLE
[User-Story] Pinned content

### ISSUE THREAD

**Issue by holisticode** [ethersphere/user-stories#10]
## Rationale ##
Until swarm is stable, it would be of great benefit to dapps if they can count on content being available from the local node at all times.

## Owner ##
@justelad 

## Stakeholder Point of Contact ##
Gregor Žavcer & Zahoor Mohamed

## Description ##
As a user, I want to upload content to my local node so that it is available at all times.
There should be HTTP APIs to do pinning operations
1) POST http://127.0.0.1:8500/bzz-pin:/<swarm-hash>  to pin an already existing swarm collection
2)POST http://127.0.0.1:8500/bzz-pin:/<swarm-hash>?raw=true to pin a existing RAW file 
3)DELETE http://127.0.0.1:8500/bzz-pin:/<swarm-hash> to unpin the hash
4) GET http://127.0.0.1:8500/bzz-pin:/ to list all the pinned files, their size, the pincounter.

## Context ##
The pinned content will be made available through the localstore infrastructure. This will require to update the setup of indexes and APIs to access, maintain and retrieve pinned content.

## Issues ##
- [x] https://github.com/ethersphere/go-ethereum/issues/1274
- [x] https://github.com/ethersphere/swarm/pull/1658

## Acceptance criteria ##
Upload a RAW file and  pin it. The file should be available at all times (for acceptance: 24hrs)
Upload a collection and pin it. The collection should be available at all times (for acceptance: 24hrs) 

## Proof ##
Download of the file or collection after 24hrs succeeds.

**Comment by acud** [comment]
The task breakdown is as follows:
1. upload with pin header flag
2. http interface for bzz-pin for PUT/DELETE for pinning just a hash/ens name
3. generalise mechanism for restricting localhost for admin functionality
4. cli interface for get/add/delete pins
5. traversal for downloading and pinning a hash
6. implement reference count in localstore
7. manage pinned content volume in connection with overall swarm volume (i.e. should not interfere with storage for regular purposes)
8. feed content pinning

this should be broken down into issues and reference this epic

**Comment by jmozah** [comment]
> this should be broken down into issues and reference this epic

Is this okay if we do like this.. 
1 base issue, 1 for pinning while uploading, 1 issue for adding http interface, 1 for feeds support

**Comment by FantasticoFox** [comment]
This is a user-story in my opinion which serves the 100 GB MVP EPIC #2 so I changed it to be a user-story. After conversations with Datafund, Elad, Zahoor Crt and Gregor technical ownership goes to Zahoor. This is now represented in our board as a userstory in review. We need to work that through next week to ensure it's containing all the elements to be fine (acceptance criteria, tests etc)

**Comment by acud** [comment]
done :heavy_check_mark:
