### ISSUE TITLE
[User-Story] See balances with other peers

### ISSUE THREAD

**Issue by holisticode** [ethersphere/user-stories#20]
## Rationale ##
Swarm is incentivized. Incentivization is based on accounting for service exchanges. During such a service exchange, the balance of service consumption and delivery is accounted for mutually between peers.

## User-Story ##
As a node operator, I want to see the balances my node has with other peers.

## Epic links ##
https://github.com/ethersphere/user-stories/issues/14

## Acceptance criteria ##
List all balances of my node with other peers by querying it via RPC.

## Requirements ##
* Write a simple command-line tool which will query balances for a node.
* RPC endpoints for query exist on a node

**Comment by vojtechsimetka** [comment]
This should be done, right @holisticode ?
