### ISSUE TITLE
[User-Story] Settle automatically

### ISSUE THREAD

**Issue by holisticode** [ethersphere/user-stories#21]
## Rationale ##
Swarm is incentivized. Incentivization is based on accounting for service exchanges. During such a service exchange, the balance of service consumption and delivery is accounted for mutually between peers.

When a node's balance in respect to a particular other peer crosses a pre-defined threshold, settlement is required.

## User-Story ##
As a node operator, I want my imbalances with other peers to be settled automatically.

## Epic links ##
https://github.com/ethersphere/user-stories/issues/14

## Acceptance criteria ##
Log of balances. The log must show:
* Balance with peer crosses threshold
* Cheques exchange
* Balance is settled

## Requirements ##
* Implementation of cheques
* Basic accounting working
* Thresholds implemented

**Comment by vojtechsimetka** [comment]
Probably done as well @holisticode ?
