### ISSUE TITLE
[User-Story] Storage node incentivisation

### ISSUE THREAD

**Issue by vojtechsimetka** [ethersphere/user-stories#24]
## Rationale ##
Participation in Swarm should be incentivised, I should be rewarded for providing storage and bandwidth.

## User-Story ##
1. I have spare capacity on my disk which I would love to get paid for.
2. I want to run server on AWS/DigitalOcean and profit on the storage I provide

## Epic links ##
#14

## Acceptance criteria ##
Easily start new node, setup payment account and start being paid for storing popular content.

## Requirements ##
- Accounting mechanism
- Garbage collection of unpopular files
- Compiled Swarm and provided through apt-get or equivalent
- AWS template
- systemd (service) or init (systemd) templates

## Related Issues ##
- #7

**Comment by nolash** [comment]
I find it unclear whether this user story is about incentivizing people to create nodes (by making it easy to run nodes), or the incentivization of the network itself.

Perhaps title should be "make money easily with swarm"

**Comment by holisticode** [comment]
I always understood this as basically "implement swap for swarm nodes"
