### ISSUE TITLE
[Upgrade] Stream! Module (Refactor pull sync)

### ISSUE THREAD

**Issue by acud** [ethersphere/user-stories#51]
## Owner ##
@acud @nonsense 

## Description ##
As a Swarm node I'd like to sync content when joining the network.
I'd like to sync new content to its correct location in the network and I'd like to sync existing content from my nodes in order to support the Swarm and help maintain content redundancy.

## Context ##
This epic is to address technical debt that we've accumulated on the existing pull syncer implementation.

## Issues ##
- [ ]  https://github.com/ethersphere/swarm/issues/1451

## Acceptance criteria ##
- syncing content should work and be measured by its retrieval

**Comment by FantasticoFox** [comment]
Changed it to User-Story as it is not a feature collection.

**Comment by FantasticoFox** [comment]
Acceptance criteria are not well enough defined. Please improve this @acud @janos 

- Smoke tests with improved performance
- No errors in logs/metrics
- Debuggable (simpler current version)

**Comment by acud** [comment]
This is done
