### ISSUE TITLE
[User-Story] Progress Bar for completed syncing of a file with swarm

### ISSUE THREAD

**Issue by FantasticoFox** [ethersphere/user-stories#6]
## Rationale ##
Allowing to tell once syncing of chunks for an uploaded file is valuable to know to share e.g. a link of a uploaded file with a friend.

IMPORTANT: THIS USER STORY IS TOO BIG - potentially other chunking of this work is required.

## User-Story ##

The uploaded gets notified by the network through their local api if the syncing is complete
it’s solved through push syncing (with tag)* (Viktor: ready to review, relied on PSS)

Functionality enabled: Upload sync confirmation for file upload status. The user knows when to share the link with his peers to allow download of the file.

## Epic link ##
EPIC #2 Datafund 100GB

## Requirements ##

- [x] Start API callback to confirm start of the sync
- [x] Call Back API to give status in % of sync
- [x] End API callback to confirm complete sync

## Dependencies ##

**Tags-Module**
Enable functionality XYZ
Please provide input to clarify @zelig @acud 
Not specified feature: Tags 
Related Issues: TBD

**Push-Sync-Module**
Enable functionally XYZ
Please provide input to clarify @zelig
Related Issues: https://github.com/ethersphere/swarm/pull/1323

**Comment by nolash** [comment]
@justelad should be part of this assignment no since he wrote `tags`?

**Comment by acud** [comment]
Yeah this one is mine.. thx @nolash

**Comment by FantasticoFox** [comment]
https://github.com/ethersphere/swarm/pull/1323

**Comment by FantasticoFox** [comment]
I need input on the dependencies @acud @zelig can you please clarify?

**Comment by FantasticoFox** [comment]
I would advice that there is a end-2-end demo with a basic front-end to complete this feature and show it to the community. I also think this could be of interest for the Datafund team and the DAPP for hosting files? @skylenet @jmozah can you check who can take on the front-end work and create an issue which is linked to this issue?
